# Generated by Django 5.1.6 on 2025-02-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='owner_id',
            new_name='user_id',
        ),
    ]
